[project]
name = "snippetvault-backend"
version = "0.1.0"
description = "Snippet Vault backend"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "bcrypt>=5.0.0",
    "black>=26.5.1",
    "fastapi>=0.142.1",
    "google-genai>=1.0.0",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.5",
    "pyjwt>=2.15.1",
    "python-dotenv>=1.2.3",
    "python-jose[cryptography]>=3.5.0",
    "python-multipart>=0.0.32",
    "sib-api-v3-sdk>=7.6.0",
    "slowapi>=0.1.10",
    "sqlalchemy>=2.1.1",
    "uvicorn[standard]>=0.54.0",
]
